### ISSUE TITLE
Can we send ETH using this?

### ISSUE THREAD

**Issue by agarwalyeshu** [merklejerk/send-tokens#13]
As I can see, currently we send only ERC20 coins, can we also send ETH? @merklejerk

**Comment by dorothy-zbornak** [comment]
[send-ether](https://github.com/merklejerk/send-ether) is the ether equivalent of this tool.

**Comment by agarwalyeshu** [comment]
Thank you so much @dorothy-zbornak 
Also, want to know that Is there any npm library like this for swapping ERC-20 coins? Like 0x/kyber ? @dorothy-zbornak @merklejerk

**Comment by dorothy-zbornak** [comment]
Full disclosure, I work for 0x. 0x does have a simple API for performing token swaps: https://0x.org/api
